fun main(){
    val numbers = mutableListOf(9, 3, 6, 2, 8, 5)
    println(numbers)
    println(numbers[0])
    println(numbers.get(0))
    //print(numbers[10])
    println(numbers.slice(2..4))
    println(numbers.first())
    println(numbers.last())
    println("Enter value to add to: ")
    val addition = readln().toInt()
    numbers.add(addition)
    println(numbers)
    numbers.remove(3)
    numbers.removeAt(0)
    println(numbers)
    numbers.clear()
    println(numbers)
}